#!/usr/bin/env bash
# Build a deterministic MANIFEST.toml in <db_dir> listing the SHA-256 of
# every file (recursively, excluding MANIFEST.toml itself).
#
# Consumed at server startup by pir-runtime-core::manifest::DbManifest
# ::load_and_verify. The SHA-256 of MANIFEST.toml itself is the
# "manifest root" the server folds into SEV-SNP REPORT_DATA when
# answering /attest.

set -euo pipefail

if [ "${1:-}" = "" ] || [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    cat >&2 <<EOF
Usage: $0 <db_dir>

Walks <db_dir> recursively, hashes every regular file (excluding
MANIFEST.toml itself), and writes MANIFEST.toml at the dir root.
Output is deterministic: paths use forward slashes and are sorted
under LC_ALL=C.

Exit codes:
  0  manifest written
  1  io error or no files found
  64 usage error
EOF
    exit 64
fi

dir="$1"
[ -d "$dir" ] || { echo "error: $dir is not a directory" >&2; exit 1; }

# sha256sum on Linux, shasum -a 256 on macOS without coreutils.
if command -v sha256sum >/dev/null 2>&1; then
    hash_one() { sha256sum "$1" | awk '{print $1}'; }
elif command -v shasum >/dev/null 2>&1; then
    hash_one() { shasum -a 256 "$1" | awk '{print $1}'; }
else
    echo "error: neither sha256sum nor shasum found on PATH" >&2
    exit 1
fi

cd "$dir"

# Collect every regular file relative to the dir, excluding MANIFEST.toml.
files_list=$(mktemp)
trap 'rm -f "$files_list"' EXIT
find . -type f ! -name MANIFEST.toml | sed 's|^\./||' | LC_ALL=C sort > "$files_list"

n=$(wc -l < "$files_list" | tr -d ' ')
if [ "$n" = "0" ]; then
    echo "error: no files to manifest in $dir" >&2
    exit 1
fi

# Write atomically: build to a temp file in the same dir, then rename.
out_tmp=$(mktemp ./MANIFEST.toml.XXXXXX)
generated_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
{
    printf '# Auto-generated by scripts/build_db_manifest.sh — do not hand-edit.\n'
    printf '# Generated at: %s\n' "$generated_at"
    printf '# Files:        %s\n' "$n"
    printf '\n'
    printf '[manifest]\n'
    printf 'version = 1\n'
    printf 'generated_at = "%s"\n' "$generated_at"
    printf '\n'
    printf '[files]\n'
    while IFS= read -r f; do
        # Cuckoo table files are several GB — skip hashing them.
        # The server (pir-runtime-core::manifest::verify_dir_contents)
        # checks their existence but skips content-hash verification;
        # the table bytes are covered by SEV-SNP MEASUREMENT instead.
        case "$f" in
            *_cuckoo.bin)
                printf '"%s" = "%s"\n' "$f" "0000000000000000000000000000000000000000000000000000000000000000"
                ;;
            *)
                h=$(hash_one "$f")
                printf '"%s" = "%s"\n' "$f" "$h"
                ;;
        esac
    done < "$files_list"
} > "$out_tmp"

mv -f "$out_tmp" MANIFEST.toml
chmod 0644 MANIFEST.toml

bytes=$(wc -c < MANIFEST.toml | tr -d ' ')
echo "wrote $(pwd)/MANIFEST.toml — covers $n files, $bytes bytes"
