#!/usr/bin/env bash
# Build a Unified Kernel Image (UKI) for BitcoinPIR's Phase 3 deployment.
#
# A UKI is a single PE/EFI file containing kernel + initrd + cmdline.
# When uploaded to a SEV-SNP host (e.g., via VPSBG's "Advanced: Measured
# Boot" UI), the entire UKI bytes get hashed into the launch MEASUREMENT
# the AMD chip signs in every attestation report. That extends the
# attested-boot chain from "OVMF only" to "OVMF + kernel + initrd + cmdline".
#
# Phase 3 Slice 1 baked the binary's SHA-256 into the kernel cmdline
# (`bpir.expected_binary_sha256=...`). Because the cmdline is part of
# the UKI, that hash is in MEASUREMENT.
#
# Phase 3 Slice 2 (this script + scripts/dracut/95bpir-verify/) adds a
# pre-pivot dracut hook that re-hashes the on-disk binary and halts
# boot via emergency_shell on mismatch. The hook ships inside the UKI's
# initramfs (built fresh via `dracut --add bpir-verify` on every run),
# so a tamper attempt on /home/pir/BitcoinPIR/target/release/unified_server
# fails the next boot visibly instead of running silently with stale or
# compromised code.
#
# Combined: an attacker now can't swap the binary on disk without either
#   (a) also rebuilding + reuploading a new UKI (operator-controlled,
#       and the new MEASUREMENT diverges from what the operator
#       publishes), or
#   (b) modifying the binary in-place at runtime (defeated by SEV-SNP
#       memory encryption + the ProtectSystem= sandbox in pir-vpsbg.service).
#
# Operator usage (must run as root — /boot/vmlinuz-* is mode 0600):
#   ssh vpsbg-pir '/home/pir/BitcoinPIR/scripts/build_uki.sh'
# then upload the printed .efi path via VPSBG dashboard → Confidentiality
# & Protection → Advanced: Measured Boot → UKI → Upload, then Save & Reboot.
#
# After the reboot, run from your laptop:
#   bpir-admin attest wss://weikeng2.bitcoinpir.org
# and capture the new MEASUREMENT — that's what you publish for verifiers.

set -euo pipefail

# Must run as root: /boot/vmlinuz-* is mode 0600 on Ubuntu.
if [ "$EUID" != "0" ]; then
    echo "error: build_uki.sh must run as root — /boot/vmlinuz-* is not" >&2
    echo "       readable by the pir user. Re-run as:" >&2
    echo "         ssh vpsbg-pir '/home/pir/BitcoinPIR/scripts/build_uki.sh'" >&2
    echo "       (default ssh user is root via your ~/.ssh/config alias.)" >&2
    exit 1
fi

# ─── Defaults (override via env) ───────────────────────────────────────────
KERNEL=${KERNEL:-/boot/vmlinuz-7.0.0-15-generic}
BINARY=${BINARY:-/home/pir/BitcoinPIR/target/release/unified_server}
ROOT_LABEL=${ROOT_LABEL:-cloudimg-rootfs}
OUT=${OUT:-/tmp/bpir.efi}
# Custom initrd path. Built fresh on every run via dracut so the bpir-verify
# pre-pivot hook is included. INITRD env var is intentionally NOT honored —
# the whole point is to build with the hook, not reuse the stock initrd.
CUSTOM_INITRD=/tmp/bpir-initrd.img

# Resolve the dracut module dir relative to this script's location so it
# works regardless of cwd. Module sources are tracked under scripts/dracut/
# (deploy/ is gitignored for local-only configs/secrets).
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
DRACUT_MODULE_SRC="$SCRIPT_DIR/dracut/95bpir-verify"

# ─── Sanity checks ─────────────────────────────────────────────────────────
for f in "$KERNEL" "$BINARY"; do
    [ -r "$f" ] || { echo "error: $f not readable" >&2; exit 1; }
done
[ -d "$DRACUT_MODULE_SRC" ] || {
    echo "error: dracut module dir missing: $DRACUT_MODULE_SRC" >&2
    exit 1
}
for tool in ukify dracut sha256sum; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "error: $tool not installed (apt install systemd-ukify dracut)" >&2
        exit 1
    }
done

# Derive kernel version from KERNEL filename (e.g. vmlinuz-7.0.0-15-generic
# → 7.0.0-15-generic). dracut needs this to find module deps under
# /usr/lib/modules/<kver>/.
KVER=$(basename "$KERNEL" | sed 's/^vmlinuz-//')
[ -d "/usr/lib/modules/$KVER" ] || {
    echo "error: /usr/lib/modules/$KVER missing — kernel modules not installed?" >&2
    exit 1
}

# ─── Install the dracut bpir-verify module ────────────────────────────────
# We install to /usr/lib/dracut/modules.d/ but DO NOT add it to the global
# /etc/dracut.conf.d/ — the module is opt-in via `--add bpir-verify`. That
# means future kernel-update autogenerated initrds (apt install linux-image-*
# triggers update-initramfs) won't pick it up. Only this script's explicit
# dracut invocation does.
DRACUT_MODULE_DST=/usr/lib/dracut/modules.d/95bpir-verify
mkdir -p "$DRACUT_MODULE_DST"
# -p preserves source mtimes. Without it, every run stamps the module .sh
# files with "now", and dracut copies those fresh mtimes into the cpio
# archive — breaking initrd determinism even with --reproducible below.
cp -fp "$DRACUT_MODULE_SRC"/*.sh "$DRACUT_MODULE_DST/"
chmod 0755 "$DRACUT_MODULE_DST"/*.sh
# Normalize mtimes to epoch 0 — see docs/PHASE3_SLICE3_REPRO_PLAN.md sub-task 1.
# `cp -fp` propagates the operator's git-clone mtime into the cpio archive,
# so even with --reproducible two fresh clones at different times produce
# different bytes. Touching to @0 closes that leak for cross-operator
# reproducibility of the Slice 2 revert artifact too.
find "$DRACUT_MODULE_DST" -type f -exec touch -d @0 {} +
echo "dracut module installed:  $DRACUT_MODULE_DST"

# ─── Compute the binary's SHA-256 (the value that ends up in cmdline) ────
if command -v sha256sum >/dev/null 2>&1; then
    BIN_HASH=$(sha256sum "$BINARY" | awk '{print $1}')
else
    BIN_HASH=$(shasum -a 256 "$BINARY" | awk '{print $1}')
fi
echo "binary:                   $BINARY"
echo "binary sha256:            $BIN_HASH"
echo "kernel:                   $KERNEL"
echo "kernel version:           $KVER"

# ─── Generate custom initrd with bpir-verify module included ──────────────
# --force overwrites any existing /tmp/bpir-initrd.img.
# --no-hostonly produces a generic initrd (works across kernel updates of
# the same KVER without re-tuning). Kept tight: only what the rootfs needs
# plus our verify hook.
echo "generating initrd with bpir-verify hook…"
# --reproducible + SOURCE_DATE_EPOCH=0 make dracut emit a byte-deterministic
# cpio: without these flags dracut stamps the archive with host file mtimes
# (and its own "now") so two runs on the same host produce different bytes.
SOURCE_DATE_EPOCH=0 dracut --force --no-hostonly --reproducible \
       --add bpir-verify \
       --kver "$KVER" \
       "$CUSTOM_INITRD"
echo "initrd:                   $CUSTOM_INITRD ($(du -h "$CUSTOM_INITRD" | cut -f1))"
INITRD="$CUSTOM_INITRD"

# ─── Build the cmdline ─────────────────────────────────────────────────────
# Standard Linux boot params + our BPIR-specific params. bpir.* keys are
# committed to MEASUREMENT (because cmdline is part of the UKI) and read
# by the bpir-verify dracut hook at pre-pivot to enforce the binary pin.
#
# Deliberately deterministic: no build timestamp, no random salt. Two
# runs of this script over the same binary produce byte-identical UKI
# bytes, so anyone holding the same binary can rebuild and verify the
# UKI hash. The git rev is captured at binary build time and reported
# via /attest, so "when was this built" is still recoverable via
# bpir-admin attest's git_rev field.
CMDLINE="root=LABEL=${ROOT_LABEL} ro console=ttyS0,115200 console=tty1 bpir.expected_binary_sha256=${BIN_HASH}"

echo "cmdline:                  $CMDLINE"
echo

# ─── Build the UKI ─────────────────────────────────────────────────────────
ukify build \
    --linux="$KERNEL" \
    --initrd="$INITRD" \
    --cmdline="$CMDLINE" \
    --output="$OUT"

# ─── Report ────────────────────────────────────────────────────────────────
SIZE=$(du -h "$OUT" | cut -f1)
UKI_SHA=$(sha256sum "$OUT" 2>/dev/null | awk '{print $1}' \
       || shasum -a 256 "$OUT" | awk '{print $1}')
echo
echo "wrote UKI:                $OUT (${SIZE})"
echo "uki sha256:               $UKI_SHA"
echo
echo "Next steps (operator):"
echo "  1. Snapshot the binary so the tamper test in step 6 is recoverable:"
echo "       cp $BINARY ${BINARY}.bak"
echo "  2. Download $OUT to your laptop:"
echo "       scp vpsbg-pir:$OUT ./bpir.efi"
echo "  3. VPSBG dashboard → Confidentiality & Protection →"
echo "     Advanced: Measured Boot → UKI → Upload bpir.efi → Save & Reboot"
echo "  4. After reboot, fetch the new MEASUREMENT:"
echo "       bpir-admin attest wss://weikeng2.bitcoinpir.org"
echo "  5. Publish the new MEASUREMENT alongside this UKI's sha256:"
echo "       UKI sha256:   $UKI_SHA"
echo "       Binary sha256: $BIN_HASH"
echo "       MEASUREMENT:  <captured from step 4>"
echo "  6. Tamper test (proves the bpir-verify hook actually halts boot):"
echo "       sudo dd if=/dev/urandom bs=1 count=1 conv=notrunc seek=1000 of=$BINARY"
echo "       reboot   # watch VPSBG VNC for [bpir-verify] FATAL: binary hash mismatch"
echo "       # then in the emergency shell: mount -o remount,rw /sysroot &&"
echo "       #   cp /sysroot${BINARY}.bak /sysroot${BINARY} && reboot"
echo "  7. Verifiers run:"
echo "       bpir-admin attest wss://weikeng2.bitcoinpir.org \\"
echo "           --expect-measurement <published MEASUREMENT> \\"
echo "           --expect-binary $BIN_HASH"
